# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BpSd-jEC6M3qVh0_cT7RgExJYD5hgrdC

dataframe
"""

import numpy as np
import pandas as pd

encuesta = pd.DataFrame({
    "julia": ["me gusto", "fue horrible"],
    "pedro": ["fue delicioso", "no estuvo mal"],
    },
    index=["restaurante_1","restaurante_2"]
)
encuesta

"""#cargar archivos csv en un dataframe

"""

#leer el archivo csv
micsv=pd.read_csv("datos.csv")
micsv.shape
micsv.head()

micsv=pd.read_csv("Games.csv")
micsv.shape
micsv.head()

micsv.describe()

micsv.rename(columns={"Score": "puntaje"}, inplace=True)

micsv.head()

mipuntaje=micsv["puntaje"]
mipuntaje.count()

mipuntaje.product()

mipuntajefiltrado=micsv[micsv["puntaje"]>1]
mipuntajefiltrado.count()

"""#titanic

"""

miserie=pd.read_csv("train_and_test2.csv")
miserie.shape
miserie.head()

miserie.rename(columns={"2urvived": "superviviente"}, inplace=True)
miserie.head()

miseriefiltrado=miserie[miserie["superviviente"]>0]
miseriefiltrado.head()
miseriefiltrado.sum()

miseriefiltrado.sum("superviviente")